version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    ignore:
        - dependency-name: "sphinx"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    labels:
      - "maintenance"
      - "dependencies"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    labels:
      - "maintenance"
    cooldown:
      default-days: 7
