ci:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

maintenance:
  - any:
      - changed-files:
        - any-glob-to-any-file: ['.github/**/*', '.pre-commit-config.yaml', 'VERSION']

testing:
  - any:
      - changed-files:
        - any-glob-to-any-file: ['tests/**/*']

documentation:
  - any:
      - changed-files:
        - any-glob-to-any-file: ['doc/**/*', 'README.rst']

dependencies:
  - any:
      - changed-files:
        - any-glob-to-any-file: ['requirements/**/*']
