[tox]
description = Automation environments for ansys/scadeone-actions repository
envlist =
    code-style
    tests
    doc-build
isolated_build = false

[testenv]
description = Base test environment
basepython = python3
passenv =
    SCADE_ONE_DIR_WINDOWS
    SCADE_ONE_DIR_LINUX

[testenv:code-style]
description = Run code style checks via pre-commit
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:doc-{clean,links,html}]
description =
    Environment for
    html: html documentation generation
    clean: cleaning previously generated html documentation
    links: verifying the integrity of external links within the documentation
skip_install = true
deps =
    links,html: -r{toxinidir}/requirements/requirements_doc.txt
setenv =
    SOURCE_DIR = doc/source
    BUILD_DIR = doc/_build
    BUILDER_OPTS = --color -v -j auto -W --keep-going
    links: BUILDER = linkcheck
    html: BUILDER = html
commands =
    clean: python -c "import shutil, sys; shutil.rmtree(sys.argv[1], ignore_errors=True)" "{toxinidir}/doc/_build"
    html,links: sphinx-build -d "{toxworkdir}/doc_doctree" {env:SOURCE_DIR} "{toxinidir}/{env:BUILD_DIR}/{env:BUILDER}" {env:BUILDER_OPTS} -b {env:BUILDER}

[testenv:tests]
description = Run Python unit tests
skip_install = true
deps =
    pytest
    -r{toxinidir}/requirements/requirements_tests.txt
setenv =
    linux: SCADE_DIR = {env:SCADE_ONE_DIR_LINUX}
    win32: SCADE_DIR = {env:SCADE_ONE_DIR_WINDOWS}
install_command = python -I -m pip install {opts} {packages} --find-links "{env:SCADE_DIR}resources/packages/pyscadeone"
commands =
    pytest --basetemp=tmp
